name: 'Turbo Remote Cache'
description: 'GitHub Action for Turborepo Remote Cache'
author: 'Vladimir'
branding:
  icon: 'zap'
  color: 'blue'
inputs:
  storage-provider:
    description: 'Storage provider (s3, azure, gcs)'
    required: true
  storage-path:
    description: 'Storage path (e.g. bucket name for S3)'
    required: true
  team-id:
    description: 'Turborepo team ID'
    required: true
  host:
    description: 'Host to bind the server to'
    required: false
    default: '127.0.0.1'
  port:
    description: 'Port to bind the server to'
    required: false
runs:
  using: 'node20'
  main: 'dist/start.js'
  post: 'dist/stop.js'
